# Generated by Django 6.0.2 on 2026-02-26 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='上课日期')),
                ('content', models.TextField(verbose_name='教学内容')),
                ('homework', models.TextField(blank=True, verbose_name='课后作业')),
                ('outstanding_students', models.TextField(blank=True, verbose_name='表现优秀学生')),
                ('improvement_students', models.TextField(blank=True, verbose_name='需要改进学生')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='classes.class', verbose_name='班级')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='课程')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '课堂总结',
                'verbose_name_plural': '课堂总结',
                'ordering': ['-date'],
                'unique_together': {('class_obj', 'date')},
            },
        ),
    ]
