# Generated by Django 6.0.2 on 2026-03-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=50, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=20, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='家长姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='家长电话'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('teacher', '老师'), ('student', '学生'), ('parent', '家长')], default='student', max_length=10, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='职称'),
        ),
    ]
