# Generated by Django 6.0.2 on 2026-02-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('suitable_items', models.TextField(help_text='多个事项用逗号分隔', verbose_name='宜')),
                ('unsuitable_items', models.TextField(help_text='多个事项用逗号分隔', verbose_name='忌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '每日趋势',
                'verbose_name_plural': '每日趋势',
                'ordering': ['-date'],
            },
        ),
    ]
