# Generated by Django 6.0.2 on 2026-02-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('O', '其他')], default='M', max_length=1, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='家长电话')),
                ('address', models.TextField(blank=True, verbose_name='家庭地址')),
                ('total_lessons', models.PositiveIntegerField(default=0, verbose_name='总课时')),
                ('remaining_lessons', models.PositiveIntegerField(default=0, verbose_name='剩余课时')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在读')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.class', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['name'],
            },
        ),
    ]
