# Generated by Django 6.0.2 on 2026-02-26 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField(verbose_name='原签到日期')),
                ('makeup_date', models.DateField(verbose_name='补签日期')),
                ('reason', models.TextField(verbose_name='补签原因')),
                ('lessons_adjusted', models.IntegerField(help_text='正数为增加课时，负数为扣除课时', verbose_name='调整课时')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_records', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '补签记录',
                'verbose_name_plural': '补签记录',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='签到日期')),
                ('status', models.CharField(choices=[('present', '已签到'), ('absent', '缺勤'), ('leave', '请假'), ('late', '迟到')], default='present', max_length=10, verbose_name='状态')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('consumed_lessons', models.PositiveIntegerField(default=1, verbose_name='消耗课时')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class', verbose_name='班级')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('student', 'date', 'class_obj')},
            },
        ),
    ]
